### ISSUE TITLE
Add configuration for What's New to run as a GitHub action

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs-tools#112]
Now that the source to the What's new in docs app is in this repo, we should add the necessary configuration / docker file to run the tool directly from this source rather than running it from a hand-generated NuGet package in each of our repos.

/cc @Rick-Anderson 

---
[Associated WorkItem - 60143](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60143)

**Comment by BillWagner** [comment]
@IEvangelist Do you want to handle this one? OR do you want to work together on it?

**Comment by IEvangelist** [comment]
@BillWagner - I'm happy to do it, but it'll have to wait a bit. When do you need this by?
