### ISSUE TITLE
Run the LocateProjects action from this repo

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs-tools#113]
The LocateProjects app is used in the Snippets5000 CI build.

Instead of running that from a hand-generated NuGet package in each repo, we should run it directly from the source in this repo.

/cc @IEvangelist @adegeo @gewarren 

Additionally, the Snippets5000 PowerShell logic should merge in with LocateProjects and have a single code base that a single maintainer can work on.

---
[Associated WorkItem - 60144](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60144)

**Comment by adegeo** [comment]
Completed!
