### ISSUE TITLE
[Sequester] Read and import Size and Sprint from the Org level projects

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs-tools#177]
When a GitHub issue is imported into AzDo or the AzDo work item is re-synced, update the *Size* project property and the *current iteration*.  

If an issue is in multiple projects, use the data from the latest (most recent) iteration. 

In order to read the V2 project data, Sequester must be be registered as an org-wide Action, and use a different authentication procedure. Those tasks are included in the list that follows.

There are several tasks that are part of this work. Those requiring help from the dotnet OSSadmins have already been completed:

- [x] Create org-wide Sequester GitHub app.
- [x] Install it in the docs related repos
  - [x] `dotnet/docs`
  - [x] `dotnet/dotnet-api-docs`
  - [x] `dotnet/csharpstandard`
  - [x] `dotnet/ASPNETCore.Docs`
  - [x] `dotnet/ASPNETCore.Docs.Samples`
  - [x] `dotnet/docs-maui`
- [x] Run the Sequester app using the new authentication policy to have an org enabled key based on the private key secret.
- [x] Update application to read project data associated with the issue. Make this code resilient enough to recover when run with the existing authentication strategies. Data should include:
  - Project name
  - Size field
- [x]  Write the updated *Size* and *iteration* data in AzDo when an issue is updated.
- [x] Create the live private key and install into each repository as a repo secret.

---
[Associated WorkItem - 71067](https://dev.azure.com/msft-skilling/Content/_workitems/edit/71067)

**Comment by BillWagner** [comment]
@mcleblanc Can you read the description above? Is that how we want to implement this.

**Comment by mcleblanc** [comment]
I think this looks correct and accurately describes how we want to implement this update.

**Comment by BillWagner** [comment]
Fiinished with a variety of PRs and configuration settings.
