### ISSUE TITLE
Comments in code blocks interpreted as H1 headings

### ISSUE THREAD

**Issue by tdykstra** [dotnet/docs-tools#205]
The preview link in this PR: https://github.com/dotnet/docs/pull/34942 was created with the wrong link text.
It interpreted as an H1 a line that begins with a single hashtag inside a code block where it was only a comment.

![image](https://user-images.githubusercontent.com/1569635/231249013-3a79c4ec-565d-4962-bfac-78b792a0662b.png)

![image](https://user-images.githubusercontent.com/1569635/231249105-c5f23d22-7c8b-478f-8fe3-530c6882ec82.png)

---
[Associated WorkItem - 87018](https://dev.azure.com/msft-skilling/Content/_workitems/edit/87018)

**Comment by IEvangelist** [comment]
Same issues realized here: https://github.com/dotnet/docs/pull/35079
