### ISSUE TITLE
The result docs don't work on IPad mini 5. Header, navigation and right side of the layout is missing from the layout

### ISSUE THREAD

**Issue by moattarwork** [dotnet/docs-tools#312]
If you browse to any learn.Microsoft.com on IPad mini 5, you can see how the layout has been rendered poorly

**Comment by BillWagner** [comment]
Hi @moattarwork 

This repo is for our teams internal tools, and isn't part of the main rendering pipeline. I've notified the folks responsible for the iPad rendering, and they've got an issue filed in their internal backlog.

Thanks for reporting this.
