### ISSUE TITLE
Install and configure dependabot for this repo

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs-tools#315]
We should make sure to have all our dependencies updated automatically in this repo.

We should have version-checker running, and dependabot should automatically update any dependent NuGet package.

**Comment by IEvangelist** [comment]
Do we want green-build dependabot PRs merged automatically? Meaning, if dependabot makes a PR, and the CI checks are all ✅ - then we automerge those?

**Comment by BillWagner** [comment]
> Do we want green-build dependabot PRs merged automatically? Meaning, if dependabot makes a PR, and the CI checks are all ✅ - then we automerge those?

I think yes. That way our automatic actions pick up any security updates quickly.
